[phases.setup]
# uses bun 1.0.18
nixpkgsArchive = '9c69bc8cae2f3b38536a50801961e2e62da13595'

[phases.build]
cmds = [
    '...',
    'bun run prisma migrate deploy',
    'bun run prisma generate',
    'ln -s /usr/lib/x86_64-linux-gnu/libssl.so /lib/libssl.so',
    'ln -s /usr/lib/x86_64-linux-gnu/libssl.so.3 /lib/libssl.so.3',
    'ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so /lib/libcrypto.so',
    'ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.3 /lib/libcrypto.so.3',
]

[start]
cmd = 'bun run start'